Removed guava lib
open-tool/ultron pull request #90
Opened 2024-09-12 07:40 UTC by itsergpot

2024-09-28 20:42 UTC, alex-tiurin requested changes

2024-09-28 20:42 UTC, alex-tiurin commented on ultron-android/src/main/kotlin/com/atiurin/ultron/custom/espresso/base/Checker.kt
> +object Checker {
Давай добавим internal модифаейр, чтобы не был это объект виден в тестах

2024-09-28 20:42 UTC, alex-tiurin commented on ultron-android/src/main/kotlin/com/atiurin/ultron/custom/espresso/base/IterableUtils.kt
> +fun <T> filter(iterable: Iterable<T>, matcher: Matcher<T>): Iterable<T> {
Тоже всем методам надо internal добавить

2024-10-02 05:27 UTC, itsergpot commented on ultron-android/src/main/kotlin/com/atiurin/ultron/custom/espresso/base/Checker.kt
> +object Checker {
rdy

2024-10-02 05:27 UTC, itsergpot commented on ultron-android/src/main/kotlin/com/atiurin/ultron/custom/espresso/base/IterableUtils.kt
> +fun <T> filter(iterable: Iterable<T>, matcher: Matcher<T>): Iterable<T> {
rdy

2024-11-30 15:03 UTC, merged